<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
    <head>
    	<!-- meta character set -->
        <meta charset="utf-8">
		<!-- Always force latest IE rendering engine or request Chrome Frame -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Munhais</title>		
		<!-- Meta Description -->
        <meta name="description" content="Munhais">
        <meta name="keywords" content="">
        <meta name="author" content="GLIMMER - Fotografía y Diseño">
		
		<!-- Mobile Specific Meta -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
		
		<link rel="shortcut icon" href="img/favicon.png">
		
		<!-- CSS
		================================================== -->
		
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
		
		<!-- Fontawesome Icon font -->
        <link rel="stylesheet" href="css/font-awesome.min.css">
		<!-- bootstrap.min -->
        <link rel="stylesheet" href="css/jquery.fancybox.css">
		
		<!-- proyectos -->
        <link rel="stylesheet" href="css/component.css">
        <link rel="stylesheet" href="css/pint.css">
		
		<!-- bootstrap.min -->
        <link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
			
		<!-- bootstrap.min -->
        <link rel="stylesheet" href="css/owl.carousel.css">
        <link rel="stylesheet" href="css/owl.css">
		<!-- bootstrap.min -->
        <link rel="stylesheet" href="css/slit-slider.css">
		<!-- bootstrap.min -->
        <link rel="stylesheet" href="css/animate.css">
		<!-- Main Stylesheet -->
        <link rel="stylesheet" href="css/main.css">

		<!-- Modernizer Script for old Browsers -->
        <script src="js/modernizr-2.6.2.min.js"></script>
		
		<!-- W3SCHOOL -->
		<script src="js/proyecto/w3.js"></script>

    </head>
	
    <body id="body">

		<!-- preloader -->
		<!-- <div id="preloader">
            <div class="loder-box">
            	<div class="battery"></div>
            </div>
		</div> -->
		<!-- end preloader -->
		
		<div w3-include-html="modals.html"></div> 

        <!--
        Fixed Navigation
        ==================================== -->
        <header id="navigation" class="navbar-inverse navbar-fixed-top animated-header">
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
                    </button>
					<!-- /responsive nav button -->
					
					<!-- logo -->
					<a href="#body"><img class="imgc1" src="img/logo.svg"></a>
					<!-- /logo -->
                </div>

				<!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="navigation">
                    <ul id="nav" class="nav navbar-nav">
                        <li><a href="#body">Inicio</a></li>
                        <li><a href="#about">Nosotros</a></li>
                        <li><a href="#service">Servicios</a></li>
                        <li><a href="#portfolio">Proyectos</a></li>
                        <li><a href="#top-contact">Contacto</a></li>
                    </ul>
					<a href="file/CV-MUNHAIS.pdf" target="_blank">
						<button type="button" class="btn btn-danger"><i class="fa fa-sign-in"></i>&nbsp; Curriculum</button>
					</a>
					<a href="https://es-la.facebook.com/pages/category/Company/MUNHAIS-SA-de-CV-166848190097429/" target="_blank">
						<i class="fa fa-facebook fa-2x socialf"></i>
					</a>
                </nav>
				<!-- /main nav -->
				
            </div>
        </header>
        <!--
        End Fixed Navigation
        ==================================== -->
		
		<main class="site-content" role="main">
		
        <!--
        Home Slider
        ==================================== -->
		
		<section id="home-slider">
            <div id="slider" class="sl-slider-wrapper" data-ride="carousel" data-interval="5000">

				<div class="sl-slider">
				
					<div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="-25" data-slice2-rotation="-25" data-slice1-scale="2" data-slice2-scale="2">

						<div class="bg-img bg-img-1"></div>

						<div class="slide-caption">
                            <div class="caption-content">
                                <h2 class="animated fadeInDown">Dinámica En construcción</h2>
                                <!-- <span class="animated fadeInDown"></span>
                                <a href="#about" class="btn btn-blue btn-effect">Bienvenido</a> -->
                            </div>
                        </div>
						
					</div>
					
					<div class="sl-slide" data-orientation="vertical" data-slice1-rotation="10" data-slice2-rotation="-15" data-slice1-scale="1.5" data-slice2-scale="1.5">
					
						<div class="bg-img bg-img-2"></div>
						<div class="slide-caption">
                            <div class="caption-content">
                                <h2>Especialistas en Mantenimiento</h2>
                                <!-- <span>Clean and Professional one page Template</span>
                                <a href="#" class="btn btn-blue btn-effect">Join US</a> -->
                            </div>
                        </div>
						
					</div>
					
					<div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="3" data-slice2-rotation="3" data-slice1-scale="2" data-slice2-scale="1">
						
						<div class="bg-img bg-img-3"></div>
						<div class="slide-caption">
                            <div class="caption-content">
                                <h2>el mejor equipo a tus órdenes</h2>
                                <!-- <span>Clean and Professional one page Template</span> -->
                                <a href="#service" class="btn btn-blue btn-effect">Ver</a>
                            </div>
                        </div>

					</div>

				</div><!-- /sl-slider -->

                <!-- 
                <nav id="nav-arrows" class="nav-arrows">
                    <span class="nav-arrow-prev">Previous</span>
                    <span class="nav-arrow-next">Next</span>
                </nav>
                -->
                
                <nav id="nav-arrows" class="nav-arrows hidden-xs hidden-sm visible-md visible-lg">
                    <a href="javascript:;" class="sl-prev">
                        <i class="fa fa-angle-left fa-3x"></i>
                    </a>
                    <a href="javascript:;" class="sl-next">
                        <i class="fa fa-angle-right fa-3x"></i>
                    </a>
                </nav>
                

				<nav id="nav-dots" class="nav-dots visible-xs visible-sm hidden-md hidden-lg">
					<span class="nav-dot-current"></span>
					<span></span>
					<span></span>
				</nav>

			</div><!-- /slider-wrapper -->
		</section>
		
        <!--
        End Home SliderEnd
        ==================================== -->
			
			<!-- about section -->
			<section id="about" >
				<div class="overlay">
					<h1 class="center">Bienvenidos</h1>
					<div class="container">
						<div class="row">
							<div class="col-md-4 wow animated fadeInLeft">
								<div class="welcome-block">
									 <div class="message-body">
										<!-- <img src="img/member-1.jpg" class="pull-left" alt="member"> -->
										<p class="justify">Munhais, S.A. de C.V., una empresa Constructora Mexicana, con amplia experiencia en el ramo, cuenta con la firme convicción de ser proveedores de servicios con una gran Calidad en sus proyectos, compromisos de entrega y respeto hacia sus clientes, ofreciendo siempre el mejor costo y tiempo.</p>
									 </div>
									<!-- <a href="#service" class="btn btn-border btn-effect pull-right">Servicios</a> -->
								</div>
							</div>
							<div class="col-md-8 wow animated fadeInRight">
								<div class="recent-works">
									<div id="works">
										<!-- <div class="work-item">
											<h3>Misión</h3>
											<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. <br> <br> There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
										</div> -->
										<div class="work-item">
											<h3>Visión</h3>
											<p>Munhais tiene la visión y el ímpetu de impulsar la Construcción Civil y Metálica a gran nivel.</p>
										</div>
										<div class="work-item">
											<h3>Valores</h3>
											<ul class="justify">
												<li>CALIDAD. Excelencia en todo lo que realizamos</li>
												<li>INTEGRIDAD. Somos éticos, justos y respetuosos</li>
												<li>SERVICIO. Trabajo en equipo, anticipar necesidades y exceder expectativas</li>
												<li>EFICIENCIA. No desperdiciamos tiempo, talento ni recursos</li>
												<li>INNOVACIÓN. Vamos siempre un paso adelante</li>
											</ul>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- end about section -->
			
			
			<!-- Service section -->
			<section id="service">
				<div class="sec-title text-center">
					<h2 class="wow animated bounceInLeft">Servicios</h2>
					<!-- <p class="wow animated bounceInRight">The Key Features of our Job</p> -->
				</div>
						
				<div class="row">
					<div class="col-md-3">
						<div class="info">
							Proyectos Ejecutivos
						</div>
					</div>
					<div class="col-md-3">
						<div class="info">
							Edificaciones metálicas y naves industriales
						</div>
					</div>
					<div class="col-md-3">
						<div class="info">
							Edificación en Obra Civil y albañilerias generales
						</div>
					</div>
					<div class="col-md-3">
						<div class="info">
							Terracerías, excavaciones y demoliciones
						</div>
					</div>
					<div class="col-md-3">
						<div class="info">
							Acabados en muros, plafones, porcelanato, etc.
						</div>
					</div>
					<div class="col-md-3">
						<div class="info">
							Mantenimientos comerciales e industriales
						</div>
					</div>
					<div class="col-md-3">
						<div class="info">
							Herrerías y cancelerías
						</div>
					</div>
					<div class="col-md-3">
						<div class="info">
							Proyectos llave en mano
						</div>
					</div>
				</div>
				
				<div class="container">
					<p class="center text">Estamos afiliados a la Cámara Nacional más importante en el ramo de la Construcción</p>
					<img class="imgc cmic" src="img/cmic.svg"> <br>
					<a href="#infoslide" class="btn btn-blue btn-effect imgc" style="width: 200px;">Ver más</a>
				</div>
			</section>
			
			<section id="infoslide">
				<div id="myCarousel" class="carousel slide" data-ride="carousel">
					<!-- Wrapper for slides -->
					<div class="carousel-inner">
						<div class="item active">
							<img src="img/bgprod1.jpg" alt="Los Angeles" style="width:100%;">
							<div class="caption animated fadeInDown" data-wow-delay="0.6s">
								<h3>CIMENTACIÓN</h3>
								<p class="justify">
									Contamos con el presonal técnico capacitado, herramientas, maquinaria y equipo para dar l a mejor atención a nuestros clientes, otorgándoles confianza y seguridad en la ejecución de sus proyectos. Además le ofrecemos asesoría en la especialidad de la cimentación profunda, orientando y dando soluciones factibles tanto en realización  como en economía pra su proyecto.<br><br>
									Nuestras especialidades en construcción de cimentación profunda a su servicio:
								</p><br>
								<ul class="justify">
									<li>Muros de contención</li>
									<li>Mejoramiento de suelos</li>
									<li>Construcción de muro Milán</li>
									<li>Cimentaciones en general</li>
									<li>Hincado de tablaestaca metálica tipo “Z”</li>
									<li>Construcción de pilotes de concreto armado</li>
									<li>Construcción de pilas de cimentación profunda coladas</li>
									<li>Construcción e hincado de tablaestaca de concreto armado</li>
								</ul>
							</div>
						</div>

						<div class="item">
							<img src="img/bgprod2.jpg" alt="Chicago" style="width:100%;">
							<div class="caption animated fadeInDown" data-wow-delay="0.6s">
								<h3>ESTRUCTURA</h3>
								<p class="justify">
									En Munhais valoramos las ventajas estéticas, económicas, ambientales y de seguridad que ofrece el trabajar con estructuras metálicas, y en base a ello contamos con una amplia experiencia la cual nos permite ofrecerle una gran variedad de servicios en lo que a este rubro corresponde. Siguiendo todas las normas y controles de calidad con el fin  de ofrecerle todas las garantías y fiabilidad.
								</p><br>
								<div class="col-xs-6 col-sm-6">
									<ul class="justify">
										<li>Estructura metálica</li>
										<li>Construcción</li>
										<li>Laminado</li>
										<li>Desmantelamiento</li>
										<li>Estacionamientos</li>
										<li>Modelado de estructura</li>
										<li>Estructuras atornilladas</li>
										<li>Estructuras soldadas en sitio</li>
									</ul>
								</div>
								<div class="col-xs-6 col-sm-6">
									<ul class="justify">
										<li>Transporte</li>
										<li>Montaje</li>
										<li>Instalaciones</li>
										<li>Edificios</li>
										<li>Mezanines</li>
										<li>Naves industriales</li>
										<li>Pintura y acabado</li>
										<li>Centros comerciales</li>
									</ul>
								</div>
							</div>
						</div>

						<div class="item">
							<img src="img/bgprod3.jpg" alt="Chicago" style="width:100%;">
							<div class="caption animated fadeInDown" data-wow-delay="0.6s">
								<h3>ACABADOS</h3>
								<p class="justify">
									Munhais trabaja siempre en cojunto con el cliente para brindar una soluciòn integral en los acabados de cada obra. De esta manera conocemos de primera mano sus necesidades, requerimientos y caracteristicas fìsicas de la obra.
									Con la información disponible de la obra, Munhais propone al cliente los productos y servicios que más se adecuan a sus requerimientos tècnicos, alcances, tiempos de ejecución y calidad del producto. Esta información permite al constructor y al diseñador decidir la mejor alternativa para su obra<br><br>
									Nuestras especialidades en acabados:<br>
								</p>
								<div class="col-xs-6 col-sm-6">
									<ul class="justify">
										<li>Interiores y exteriores</li>
										<li>Pintura en general</li>
										<li>Plafones y cajillos</li>
										<li>Cancelería</li>
										<li>Porcelanatos</li>
										<li>Granito</li>
									</ul>
								</div>
								<div class="col-xs-6 col-sm-6">
									<ul class="justify">
										<li>Tablaroca y Durock</li>
										<li>Texturizados</li>
										<li>Yeso</li>
										<li>Acabado en pisos</li>
										<li>Marmol</li>
										<li>Herrería</li>
									</ul>
								</div>
							</div>
						</div>

						<div class="item">
							<img src="img/bgprod4.jpg" alt="Chicago" style="width:100%;">
							<div class="caption animated fadeInDown" data-wow-delay="0.6s">
								<h3>TABLAROCA DUROCK</h3>
								<p class="justify">
									Soluciones de construcción ligera, acabados con material y mano de obra garantizados.
								</p><br>
								<div class="col-xs-6 col-sm-6">
									<ul class="justify">
										<li>Muros</li>
										<li>Cubículos</li>
										<li>Cielo falso</li>
										<li>Plafones</li>
										<li>Fachadas</li>
										<li>Aparadores</li>
									</ul>
								</div>
								<div class="col-xs-6 col-sm-6">
									<ul class="justify">
										<li>Mamparas</li>
										<li>Módulos</li>
										<li>Paredes divisorias</li>
										<li>Oficinas</li>
										<li>Detalles</li>
										<li>Diseños especiales</li>
									</ul>
								</div>
							</div>
						</div>

						<div class="item">
							<img src="img/bgprod5.jpg" alt="Chicago" style="width:100%;">
							<div class="caption animated fadeInDown" data-wow-delay="0.6s">
								<h3>OBRA CIVIL</h3>
								<p class="justify">
									A través de nuestro segmento de construcción de obra civil, realizamos importantes proyectos de infraestructura, que incluyen la construcción y rehabilitación de estructuras de concreto, cimentaciones, pavimentaciones, caminos de acceso a instalaciones, drenajes pluviales y edificios en general, que implican el diseño y la ingeniería para realizar la correcta construcción de los elementos estructurales prefabricados en nuestro patio.
								</p><br>
								<div class="col-xs-6 col-sm-6">
									<ul class="justify">
										<li>Firmes</li>
										<li>Losas de cimentación</li>
										<li>Muros de contensión</li>
										<li>Zarpeos</li>
										<li>Cisternas</li>
									</ul>
								</div>
								<div class="col-xs-6 col-sm-6">
									<ul class="justify">
										<li>Losas de concreto</li>
										<li>Muros colados</li>
										<li>Muros de block</li>
										<li>Banquetas</li>
										<li>Estructuración</li>
									</ul>
								</div>
							</div>
						</div>

						<div class="item">
							<img src="img/bgprod6.jpg" alt="New york" style="width:100%;">
							<div class="caption animated fadeInDown" data-wow-delay="0.6s">
								<h3>MUNHAIS CONSTRUCTORA</h3>
								<p class="justify">
									Contamos con el presonal técnico capacitado, herramientas, maquinaria y equipo para dar l a mejor atención a nuestros clientes, otorgándoles confianza y seguridad en la ejecución de sus proyectos. Además le ofrecemos asesoría en la especialidad de la cimentación profunda, orientando y dando soluciones factibles tanto en realización  como en economía pra su proyecto.<br><br>
									Nuestras especialidades en construcción de cimentación profunda a su servicio:
								</p><br>
								<ul class="justify">
									<li>Muros de contención</li>
									<li>Mejoramiento de suelos</li>
									<li>Construcción de muro Milán</li>
									<li>Cimentaciones en general</li>
									<li>Hincado de tablaestaca metálica tipo “Z”</li>
									<li>Construcción de pilotes de concreto armado</li>
									<li>Construcción de pilas de cimentación profunda coladas</li>
									<li>Construcción e hincado de tablaestaca de concreto armado</li>
								</ul>
							</div>
						</div>
					</div>

					<!-- Left and right controls -->
					<a class="left carousel-control" href="#myCarousel" data-slide="prev">
						<span class="glyphicon glyphicon-chevron-left"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="right carousel-control" href="#myCarousel" data-slide="next">
						<span class="glyphicon glyphicon-chevron-right"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
			</section>
			<!-- <section id="service1">
				
			</section> -->
			<!-- end Service section -->
			
			<section id="clientes">
				<div class="sec-title text-center wow animated fadeInDown">
					<h2>CLIENTES</h2>
				</div>
				<div id="owl-demo">
					<div class="item">
						<img src="img/client1.png">
					</div>
					<div class="item">
						<img src="img/client2.png">
					</div>
					<div class="item">
						<img src="img/client3.png">
					</div>
					<div class="item">
						<img src="img/client4.png">
					</div>
					<div class="item">
						<img src="img/client5.png">
					</div>
					<div class="item">
						<img src="img/client6.png">
					</div>
					<div class="item">
						<img src="img/client7.png">
					</div>
					<div class="item">
						<img src="img/client8.png">
					</div>
					<div class="item">
						<img src="img/client9.png">
					</div>
					<div class="item">
						<img src="img/client10.png">
					</div>
					<div class="item">
						<img src="img/client11.png">
					</div>
					<div class="item">
						<img src="img/client12.png">
					</div>
					<div class="item">
						<img src="img/client13.png">
					</div>
					<div class="item">
						<img src="img/client14.png">
					</div>
					<div class="item">
						<img src="img/client15.png">
					</div>
					<div class="item">
						<img src="img/client16.png">
					</div>
					<div class="item">
						<img src="img/client17.png">
					</div>
					<div class="item">
						<img src="img/client18.png">
					</div>
					<div class="item">
						<img src="img/client19.png">
					</div>
					<div class="item">
						<img src="img/client20.png">
					</div>
					<div class="item">
						<img src="img/client21.png">
					</div>
					<div class="item">
						<img src="img/client22.png">
					</div>
				</div>
			</section>
			
			<!-- portfolio section -->
			<section id="portfolio">
			
				<div class="sec-title text-center wow animated fadeInDown">
					<h2>PROYECTOS</h2>
					<!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p> -->
				</div>
				
				<ul class="grid cs-style-3">
					<li>
						<figure>
							<img src="img/4.png" alt="img03">
							<figcaption>
								<h3>Estacionamiento Club Alpino</h3>
								<a href="" data-toggle="modal" data-target="#pro1" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-coppel.jpg" alt="img03">
							<figcaption>
								<h3>Coppel</h3>
								<a href="" data-toggle="modal" data-target="#pro2" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-braden.jpg" alt="img03">
							<figcaption>
								<h3>Braden</h3>
								<a href="" data-toggle="modal" data-target="#pro3" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-gonher.jpg" alt="img03">
							<figcaption>
								<h3>Gonher</h3>
								<a href="" data-toggle="modal" data-target="#pro4" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-acero.jpg" alt="img03">
							<figcaption>
								<h3>De Acero</h3>
								<a href="" data-toggle="modal" data-target="#pro5" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-logrand.jpg" alt="img03">
							<figcaption>
								<h3>Logrand</h3>
								<a href="" data-toggle="modal" data-target="#pro6" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-tec.jpg" alt="img03">
							<figcaption>
								<h3>Universidad Tec Milenio</h3>
								<a href="" data-toggle="modal" data-target="#pro7" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-hilton.jpg" alt="img03">
							<figcaption>
								<h3>Hilton</h3>
								<a href="" data-toggle="modal" data-target="#pro8" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-mabe.jpg" alt="img03">
							<figcaption>
								<h3>Mabe</h3>
								<a href="" data-toggle="modal" data-target="#pro9" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-esfera.jpg" alt="img03">
							<figcaption>
								<h3>Torre Esfera Monterrey</h3>
								<a href="" data-toggle="modal" data-target="#pro10" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-nemak.jpg" alt="img03">
							<figcaption>
								<h3>Nemak</h3>
								<a href="" data-toggle="modal" data-target="#pro11" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-thyssen.jpg" alt="img03">
							<figcaption>
								<h3>Thyssenkrupp</h3>
								<a href="" data-toggle="modal" data-target="#pro12" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-dypco.jpg" alt="img03">
							<figcaption>
								<h3>Dypco</h3>
								<a href="" data-toggle="modal" data-target="#pro13" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-xportal.jpg" alt="img03">
							<figcaption>
								<h3>Xportal</h3>
								<a href="" data-toggle="modal" data-target="#pro14" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-sorteo.jpg" alt="img03">
							<figcaption>
								<h3>Sorteo TEC</h3>
								<a href="" data-toggle="modal" data-target="#pro15" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<img src="img/pro-siemens.jpg" alt="img03">
							<figcaption>
								<h3>Siemens</h3>
								<a href="" data-toggle="modal" data-target="#pro16" class="btn btn-blue btn-effect imgc" style="width: 70px;">Ver</a>
							</figcaption>
						</figure>
					</li>
				</ul>
				
				<!-- <div class="container">
					<div class="row">
								
						<ul class="project-wrapper wow animated fadeInUp">
							<li class="portfolio-item">
								<img src="img/proyectos/alpino01.jpg" class="img-responsive" alt="Ubicación, San Pedro Garza García Nuevo León.<br> Obra 240 ton. Estructura Metálica.<br> Cliente: Grupo Dipco.">
								<figcaption class="mask">
									<h3>Estacionamiento Club Alpino </h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Estacionamiento Club Alpino" data-fancybox-group="works" href="img/pdf/CV-MUNHAIS-012.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/pdf/CV-MUNHAIS-051.jpg" class="img-responsive" alt="Ubicación: García Nuevo León.<br> Obra: Proyecto llave en mano, Terracerías, Cimentación, Estructura metálica, Laminación, Firmes.<br> Cliente: Braden Manufacturing">
								<figcaption class="mask">
									<h3>Nave Pintura y Sanblast</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Nave Pintura y Sanblast" href="img/pdf/CV-MUNHAIS-051.jpg" data-fancybox-group="works" ><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: Chihuahua, Chihuahua.<br> Obra: Tablaroca, Pisos, Plafones, Iluminación e Instalación Eléctrica.">
								<figcaption class="mask">
									<h3>Torre Sphera</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Torre Sphera" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: Santa Catarina, Nuevo León.<br> Obra: 70 ton. de estructura metálica.">
								<figcaption class="mask">
									<h3>Oficinas de Tecnología</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Oficinas de Tecnología" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: San Pedro Garza García, Nuevo León.<br> Obra: Servicio y Renta de Operación de Maquinaria Pesada 24/7.<br> Cliente: Nemak.">
								<figcaption class="mask">
									<h3>Centro Fusor Nemak</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Centro Fusor Nemak" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: Santa Catarina, Nuevo León.<br> Obra: 9000 m2 de Estacionamiento, Terracerías, Pavimentación y Alumbrado Solar.<br> Cliente: Siemens.">
								<figcaption class="mask">
									<h3>Estacionamiento Siemens</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Estacionamiento Siemens" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: García, Nuevo León.<br> Obra: Proyecto llave en mano, Terracerías, Cimentación, Estructura Metálica, Laminación, Instalaciones Eléctricas.">
								<figcaption class="mask">
									<h3>Nave para Almacen</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Nave para Almacen" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: San Pedro Garza García, Nuevo León.<br> Obra: Proyecto llave en mano, Demoliciones, Albañilerias, Estructura Metálica e Iluminación.<br> Cliente: Club Campestre.">
								<figcaption class="mask">
									<h3>Club Campestre de Monterrey</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Club Campestre de Monterrey" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Obra: Estructura metálica para cubo de Suites, puente de interconexión a Terminal.">
								<figcaption class="mask">
									<h3>Hotel Hilton Aeropuerto Monterrey</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Hotel Hilton Aeropuerto Monterrey" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: Monterrey, Nuevo León.<br> Obra: Estructura metálica, laminación en auditorio,  gimnasio, preescolar, canchas y dropoff">
								<figcaption class="mask">
									<h3>Colegio West Heights</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Colegio West Heights" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: Aguascalientes, Aguascalientes. <br> Obra: Proyecto llave en mano, terracerías, cimentación, estructura metálica, laminación y firmes.<br> Cliente: Vitro.">
								<figcaption class="mask">
									<h3>Nave Satelite 2 / Vitro</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Nave Satelite 2 / Vitro" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: San Pedro Garza García.<br> Obra: Terracerías, Cimentación, Estructura Metálica, Rampa de Acero.<br> Cliente: Granero Grill.">
								<figcaption class="mask">
									<h3>Planta Tractebel</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Planta Tractebel" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: Monterrey, Nuevo León.<br> Obra: Carpintería, Pintura e Instalaciones Eléctricas.<br> Cliente: Logrand Group">
								<figcaption class="mask">
									<h3>Restaurant Casino Jubilee</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Restaurant Casino Jubilee" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: Guadalupe, Nuevo León.<br> Obra: 760 ton. de Estructura Metálica, Losacero y Rampas.<br> Cliente: Grupo Dypco.">
								<figcaption class="mask">
									<h3>Tec Milenio Guadalupe</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Tec Milenio Guadalupe" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: Santa Catarina, Nuevo Léon.<br> Obra: Estructura Metálica, Multypanel, Losacero y Laminación.<br> Cliente: Siemens.">
								<figcaption class="mask">
									<h3>Laboratorios / Oficinas / Taller</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Laboratorios / Oficinas / Taller" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: Monterrey, Nuevo León.<br> Obra: Muros de Contención, Muros de Block y Albañilerias.<br> Cliente: Vitro.">
								<figcaption class="mask">
									<h3>Oficinas Sindicato Vitro Fama</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Oficinas Sindicato Vitro Fama" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: Monterrey, Nuevo León.<br> Obra: Estructuración en cubo de elevadores, 50 pisos realizado en 30 días (24 hrs.)<br> Cliente: Grupo Dypco.">
								<figcaption class="mask">
									<h3>Tec Milenio Guadalupe</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Tec Milenio Guadalupe" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: Durango, Durango.<br> Obra: 80 ton. de estructura metálica, losacero, pergolados, puente y cafetería.<br> Cliente: Grupo Dypco.">
								<figcaption class="mask">
									<h3>Tec Milenio Durango</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Tec Milenio Durango" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: San Pedro Garza García.<br> Obra: 110 ton. dde estructura metálica concava rolada y laminación.">
								<figcaption class="mask">
									<h3>Paraolimpico Estatal DIF</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Paraolimpico Estatal DIF" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: Chihuahua, Chihuahua.<br> Obra: 120 ton. de estructura metálica y 1,350 m2 de losacero.<br> Cliente: Grupo Dypco.">
								<figcaption class="mask">
									<h3>Ampliación Aeropuerto Chihuahua</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Ampliación Aeropuerto Chihuahua" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
							
							<li class="portfolio-item">
								<img src="img/thumb.jpg" class="img-responsive" alt="Ubicación: Guadalajara, Jalisco.<br> Obra: 120 ton. de estructura metálica y 2,300 m2 de Multipanel.">
								<figcaption class="mask">
									<h3>Nave Desert Glory</h3>
								</figcaption>
								<ul class="external">
									<li><a class="fancybox" title="Nave Desert Glory" data-fancybox-group="works" href="img/construccion.jpg"><i class="fa fa-eye"></i></a></li>
								</ul>
							</li>
						</ul>
						
					</div>
				</div> -->
			</section>
			<!-- end portfolio section -->
			
			<!-- Social section -->
			<section id="social" class="parallax">
				<div class="overlay">
					<div class="container">
						<div class="row">
						
							<div class="sec-title text-center white wow animated fadeInDown">
								<h2>Siguenos</h2>
								<p>Unete a nuestras redes sociales</p>
							</div>
							
							<ul class="social-button">
								<li class="wow animated zoomIn" data-wow-delay="0.3s"><a href="https://es-la.facebook.com/pages/category/Company/MUNHAIS-SA-de-CV-166848190097429/" target="_blank"><i class="fa fa-facebook fa-2x"></i></a></li>
								<li class="wow animated zoomIn" data-wow-delay="0.6s">
									<a title="Click para chatear" href="https://api.whatsapp.com/send?phone=5218110747469&amp;text=Hola%2C%20deseo%20saber%20mas%20informacion%20y%20Cotizacion" target="_blank">
										<i class="fa fa-whatsapp fa-2x"></i>
									</a>
								</li>							
							</ul>
							
						</div>
					</div>
				</div>
			</section>
			<!-- end Social section -->
			
			<section id="top-contact">
				<div class="container center">
					Esperamos nos permita colaborar en alguno de sus importantes proyectos, quedamos a su entera disposición en nuestras líneas de contacto.
				</div>
			</section>
			
			<!-- Contact section -->
			<section id="contact" >
				<div class="container">
					<div class="row">
						
						<div class="sec-title text-center wow animated fadeInDown">
							<h2>Contacto</h2>
							<p>Déjanos un Mensaje</p>
						</div>
						<div class="col-md-3"></div>
						<div class="col-md-6 wow animated fadeInRight">
							<address class="contact-details">
								<h3>Contáctanos</h3>						
								<p><i class="fa fa-pencil"></i>Guatemala 202<span>Col. Vista hermosa</span> <span>Monterrey, Nuevo León </span><span>México</span></p><br>
								<p><i class="fa fa-phone"></i>Teléfono: <a href="tel: 81 8393 9946">(81) 8393. 9946</a> </p>
								<p><i class="fa fa-envelope"></i><a href="mailto: contacto@munhais.com">contacto@munhais.com</a></p>
							</address>
						</div>
						<div class="col-md-3"></div>
			
					</div>
				</div>
			</section>
			<!-- end Contact section -->
			
			<!-- <section id="google-map">
				<div id="map-canvas" class="wow animated fadeInUp"></div>
			</section> -->
			
			<section id="maps">
				<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d4275.028100547541!2d-100.34350031856621!3d25.709197829167024!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses!2smx!4v1544921078610" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
			</section>
		
		</main>
		
		<footer id="footer">
			<div class="container">
				<div class="row text-center">
					<div class="footer-content">
						<div class="wow animated fadeInDown">
							<img class="imgc" src="img/logo1.svg">
						</div>
						<!-- <form action="#" method="post" class="subscribe-form wow animated fadeInUp">
							<div class="input-field">
								<input type="email" class="subscribe form-control" placeholder="Enter Your Email...">
								<button type="submit" class="submit-icon">
									<i class="fa fa-paper-plane fa-lg"></i>
								</button>
							</div>
						</form> -->
						<div class="footer-social">
							<ul>
								<li class="wow animated zoomIn" data-wow-delay="0.3s"><a href="https://es-la.facebook.com/pages/category/Company/MUNHAIS-SA-de-CV-166848190097429/" target="_blank"><i class="fa fa-facebook fa-3x"></i></a></li>
								<li class="wow animated zoomIn" data-wow-delay="0.6s">
									<a title="Click para chatear" href="https://api.whatsapp.com/send?phone=5218110747469&amp;text=Hola%2C%20deseo%20saber%20mas%20informacion%20y%20Cotizacion" target="_blank">
										<i class="fa fa-whatsapp fa-3x"></i>
									</a>
								</li>
							</ul>
						</div>
						
						<p>Copyright &copy; 2019 <!-- Design and Developed By<a href="http://www.munhais.com">Munhais</a> --> </p>
					</div>
				</div>
			</div>
		</footer>
		
		
		<!-- Essential jQuery Plugins
		================================================== -->
		<!-- Main jQuery -->
        <script src="js/jquery-1.11.1.min.js"></script>
		<!-- Twitter Bootstrap -->
        <script src="js/bootstrap.min.js"></script>
		<!-- Single Page Nav -->
        <script src="js/jquery.singlePageNav.min.js"></script>
		<!-- jquery.fancybox.pack -->
        <script src="js/jquery.fancybox.pack.js"></script>
		<!-- Google Map API -->
		<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
		<!-- Owl Carousel -->
        <script src="js/owl.carousel.min.js"></script>
        <script src="js/owl.js"></script>
        <script src="js/toucheffects.js"></script>
        <!-- jquery easing -->
        <script src="js/jquery.easing.min.js"></script>
        <!-- Fullscreen slider -->
        <script src="js/jquery.slitslider.js"></script>
        <script src="js/jquery.ba-cond.min.js"></script>
		<!-- onscroll animation -->
        <script src="js/wow.min.js"></script>
		<!-- Custom Functions -->
        <script src="js/main.js"></script>
		
		<!-- <script src="//tympanus.net/codrops/adpacks/demoad.js"></script> -->
		
		<script>
			w3.includeHTML();
		</script>
		
		 <script src="https://www.google.com/recaptcha/api.js?render=6LfPi8kZAAAAAF-O8YXT9RttZ6d8mAZ2dHzhb6wQ"></script>

         <script>
              function onClick(e) {
                e.preventDefault();
                grecaptcha.ready(function() {
                  grecaptcha.execute('6LfPi8kZAAAAAF-O8YXT9RttZ6d8mAZ2dHzhb6wQ', {action: 'submit'}).then(function(token) {
                      // Add your logic to submit to your backend server here.
                  });
                });
              }
          </script>
		
    </body>
</html>
